# Docker-Compose definition for a locally mapped Postgres database

version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.data:/var/lib/postgresql/data
    ports:
      - 5432:5432